Genre.find_or_create_by(name: "Action & Adventure")
Genre.find_or_create_by(name: "Classics")
Genre.find_or_create_by(name: "Comic Book or Graphic Novel")
Genre.find_or_create_by(name: "Detective & Mystery")
Genre.find_or_create_by(name: "Fantasy")
Genre.find_or_create_by(name: "Historical Fiction")
Genre.find_or_create_by(name: "Horror")
Genre.find_or_create_by(name: "Literary Fiction")
Genre.find_or_create_by(name: "Romance")
Genre.find_or_create_by(name: "Science Fiction")
Genre.find_or_create_by(name: "Short Stories")
Genre.find_or_create_by(name: "Suspense & Thrillers")
Genre.find_or_create_by(name: "Biographies & Autobiographies")
Genre.find_or_create_by(name: "Cookbooks")
Genre.find_or_create_by(name: "Essays")
Genre.find_or_create_by(name: "History")
Genre.find_or_create_by(name: "Memoir")
Genre.find_or_create_by(name: "Poetry")
Genre.find_or_create_by(name: "Self-Help")
Genre.find_or_create_by(name: "True Crime")

# Front end created user information (email: "michael@michael.com", first_name: "Michael", last_name: "Royce", password_digest: "3089")
# Front end created user information (email: "ollie@brandtson.com", first_name: "Oliver", last_name: "Rush", password_digest: "5555")
