User.find_or_create_by(email: "patrick@patrick.com", first_name: "Patrick", last_name: "Rush", password_digest: "8920")
User.find_or_create_by(email: "test@test.com", first_name: "Testy", last_name: "McTesterson", password_digest: "2049")
# Front end created user information (email: "michael@michael.com", first_name: "Michael", last_name: "Royce", password_digest: "3089")
# Front end created user information (email: "ollie@brandtson.com", first_name: "Oliver", last_name: "Rush", password_digest: "5555")

Book.find_or_create_by(title: "Terrible Book", author: "Steven", status: "read", user_id: "1")
Book.find_or_create_by(title: "Bad Book", author: "Jerry", status: "unread", user_id: "1")
Book.find_or_create_by(title: "Neutral Book", author: "Tina", status: "reading", user_id: "1")
Book.find_or_create_by(title: "Good Book", author: "Elizabeth", status: "", user_id: "1")
Book.find_or_create_by(title: "Incredible Book", author: "God", status: "read", user_id: "1")
Book.find_or_create_by(title: "Terrible Book", author: "Steven", status: "read", user_id: "2")
Book.find_or_create_by(title: "Bad Book", author: "Jerry", status: "unread", user_id: "2")
Book.find_or_create_by(title: "Neutral Book", author: "Tina", status: "reading", user_id: "2")
Book.find_or_create_by(title: "Good Book", author: "Elizabeth", status: "", user_id: "2")
Book.find_or_create_by(title: "Incredible Book", author: "God", status: "read", user_id: "2")

Note.find_or_create_by(content: "I don't even know what to type", book_id: "1")
Note.find_or_create_by(content: "To be or not to be", book_id: "1")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "1")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "1")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "1")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "2")
Note.find_or_create_by(content: "To be or not to be", book_id: "2")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "2")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "2")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "2")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "3")
Note.find_or_create_by(content: "To be or not to be", book_id: "3")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "3")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "3")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "3")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "4")
Note.find_or_create_by(content: "To be or not to be", book_id: "4")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "4")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "4")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "4")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "5")
Note.find_or_create_by(content: "To be or not to be", book_id: "5")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "5")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "5")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "5")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "6")
Note.find_or_create_by(content: "To be or not to be", book_id: "6")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "6")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "6")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "6")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "7")
Note.find_or_create_by(content: "To be or not to be", book_id: "7")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "7")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "7")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "7")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "8")
Note.find_or_create_by(content: "To be or not to be", book_id: "8")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "8")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "8")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "8")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "9")
Note.find_or_create_by(content: "To be or not to be", book_id: "9")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "9")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "9")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "9")
Note.find_or_create_by(content: "I don't even know what to type", book_id: "10")
Note.find_or_create_by(content: "To be or not to be", book_id: "10")
Note.find_or_create_by(content: "It was the best of times it was the worst of times", book_id: "10")
Note.find_or_create_by(content: "There was a boy named Eustice Clerance Scrubb, and he almost deserved it", book_id: "10")
Note.find_or_create_by(content: "Let there be LIGHT", book_id: "10")
